# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain-alias:
          - msrv
          - stable
        include:
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Check a package
        run: wasm-pack build -s sorairolake -t nodejs --dev

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain-alias:
          - msrv
          - stable
        include:
          - toolchain-alias: msrv
            toolchain: 1.85.0
          - toolchain-alias: stable
            toolchain: stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Run tests
        run: wasm-pack test --node

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Check code formatted
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Check no lint warnings
        run: cargo clippy -- -D warnings

  doc:
    name: Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Check no `rustdoc` lint warnings
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --document-private-items --all-features

  wasm-examples:
    name: Examples for the Wasm bindings
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v1.x
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.8
      - name: Check code formatted
        run: deno fmt --check examples/*.ts
      - name: Check no lint warnings
        run: deno lint examples/*.ts
      - name: Type-check
        run: |
          wasm-pack build -t deno --dev
          deno check examples/*.ts
